networks:
  rest_bridge:

services:
  rest:
    image: apache/iceberg-rest-fixture
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - CATALOG_CATALOG__IMPL=org.apache.iceberg.jdbc.JdbcCatalog
      - CATALOG_URI=jdbc:sqlite:file:/tmp/iceberg_rest_mode=memory
      - CATALOG_WAREHOUSE=s3://${S3_BUCKET}/${S3_PATH}
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
    networks:
      rest_bridge:
    ports:
      - "8181:8181" 